name: program_b30
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  easy_sidemenu: ^0.3.1
  graphic: ^0.10.5
  quiver: ^3.0.1+1
  intl: ^0.17.0
  cached_network_image: ^3.2.0
  flutter:
    sdk: flutter
  get: 4.6.5

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
